### ISSUE TITLE
[Feature Request] Add support for secrets

### ISSUE THREAD

**Issue by david6983** [arttor/helmify#1]
In `kustomization.yaml` it is possible to generate secrets using `secretGenerator`:

```yaml
secretGenerator:
- files:
  - ca.crt
  name: ca
  type: opaque
- envs:
  - envfile.env
  name: my-secret
  type: opaque
```

I would like the `helmify` tool to generate the secrets in the Helm Chart output.

**Comment by arttor** [comment]
Hi @david6983 !
Can you please also provide an example of usage for secrets? Will it be used only in deployment or in cert issuer or somewhere else?

**Comment by david6983** [comment]
> Hi @david6983 !
> Can you please also provide an example of usage for secrets? Will it be used only in deployment or in cert issuer or somewhere else?
> I am asking because we also need to change secretName to templated name in the place of usage. For example in `deployment.yaml`:
> 
> ```yaml
> spec:
>   volumes:
>   - name: secret-volume
>     secret:
>       secretName: my-secret
>   containers:
>   - name: my-container
>     volumeMounts:
>     - name: secret-volume
>       mountPath: "/etc/secret-volume"
>     envFrom:
>       - secretRef:
>           name: my-secret
>   ...
> ```
> 
> Should be changed to:
> 
> ```yaml
> spec:
>   volumes:
>   - name: secret-volume
>     secret:
>       secretName: {{ include "mychart.fullname" . }}-my-secret
>   containers:
>   - name: my-container
>     volumeMounts:
>     - name: secret-volume
>       mountPath: "/etc/secret-volume"
>     envFrom:
>       - secretRef:
>           name: {{ include "mychart.fullname" . }}-my-secret
>   ...
> ```

Those secrets will be used for a deployment for example, let's say a container in a deployment need the ca.crt:

```yaml
containers:
- command:
  - /manager
  args:
  - --leader-elect
  image: controller:latest
  imagePullPolicy: Always
  volumeMounts:
    - name: custom-ca
      mountPath: /etc/ssl/certs/ca.crt
      subPath: ca.crt
      readOnly: true
  env:
    - name: CUSTOM_CA
      valueFrom:
        secretKeyRef:
          name: custom-ca
          key: ca.crt
```

In `kustomization.yaml`

```yaml
secretGenerator:
- files:
  - ca.crt
  name: custom-ca
  type: opaque
```

I will try to modify my pull requests accordingly then
