### ISSUE TITLE
Secret value not transferred to output values.yaml

### ISSUE THREAD

**Issue by Vaintti** [arttor/helmify#103]
I have a secret defined in a kubernetes yaml file but the value doesn't get transferred to generated `values.yaml` file

**Input**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  password: c3VwZXJzZWNyZXRwYXNzd29yZAo=
```

**Output**
```yaml
dbPassword:
  password: ""
kubernetesClusterDomain: cluster.local
```

**Expected output**
```yaml
dbPassword:
  password: "supersecretpassword"
kubernetesClusterDomain: cluster.local
```
