### ISSUE TITLE
Allow specifying custom labels and annotations from values.yaml

### ISSUE THREAD

**Issue by Jay-Madden** [arttor/helmify#119]
We have a need to add specific annotations to helm chart releases per environment. Adding a way to set those at helm install time would be very helpful. 

If this is a useful feature i would be willing to contribute it myself if desired

**Comment by arttor** [comment]
Hi, can you please share more details on your use case?

If I got you right, Helm already does similar stuff for labels. There is a named template in `_helpers.tpl` 
```yaml
{{/*
Common labels
*/}}
{{- define "app.labels" -}}
helm.sh/chart: {{ include "app.chart" . }}
{{ include "app.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
```

And then these labels are added to all chart manifests:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-myapp
  labels:
    app: myapp
  {{- include "app.labels" . | nindent 4 }}
```
Which results to:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-myapp
  labels:
    app: myapp
    helm.sh/chart: app-0.1.0
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
```

You can modify `app.labels` to add some env-specific labels or create a similar template for annotations.
I am not fully aware of your use case but it is not very common to provide the same set of annotations to all chart manifests.


PS
Recently we added a processor for ServiceAccount annotations in #115.
So if the desired behavior is to extract annotation from source manifests into values.yaml, you can use `WithAnnotations` option for other resource processors (not only ServiceAccount) - see https://github.com/arttor/helmify/blob/main/pkg/processor/rbac/serviceaccount.go#L30. 
SericeAccount annotations processor was added to the main branch because it is a very common use case for cloud environments.
