### ISSUE TITLE
Incorrect labels for StatefulSet selector section

### ISSUE THREAD

**Issue by andreiionutdamian** [arttor/helmify#131]
The problem is that the `StatefulSet` are not correctly generated resulting in the service not being able to correctly select coresponding pods. Basically I had this original manifest (part):
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  ...
```
after helmify I received:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sf.fullname" . }}-master
  labels:
    app: redis
    role: master
  {{- include "sf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: redis
      role: master
  serviceName: ""
  template:
    metadata:
      labels:
        app: redis
        role: master
    ...
```
So the `specs.selector.matchLabels` and the `spec.template.metadata.labels` are missing a `{{- include "<chart>.selectorLabels" . | nindent 6 }}` while the service template has it as it should. I replicated the identical scenario with `Deployment` instead of `StatefulSet` and in the case of `Deployment` the results are correct as it is supposed to be (and service-pods communication works):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
  {{- include "stateless.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: redis
      role: master
    {{- include "stateless.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: redis
        role: master
      {{- include "stateless.selectorLabels" . | nindent 8 }}
```
