### ISSUE TITLE
Single quote dropped.

### ISSUE THREAD

**Issue by dmolik** [arttor/helmify#151]
In one of my operator deployments I'm including a metadata field in the envs like so:
```yaml
        env:
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/name']
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/instance']
```

when piped through helmify the single quotes are dropped.
