### ISSUE TITLE
imagePullSecrets field should be generated in values.yaml and deployment.yaml should reference it from values

### ISSUE THREAD

**Issue by barkhachoithani** [arttor/helmify#164]
We have a Go-based Operator, and we're using **Helmify** to generate the Helm chart for it. In the operator’s` manager.yaml `file, we've defined `imagePullSecrets`, which is then used to create the `deployment.yaml` within the Helm chart. The issue we're facing is that the `imagePullSecrets` field from `manager.yaml `is being directly mapped to `deployment.yaml` with its default value, instead of generating this field in `values.yaml` and referencing it in `deployment.yaml`. Please note `imagePullSecrets` is part of `deployment->template->spec` in the `manager.yaml` file.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      imagePullSecrets: 
        - name: "myRegCredentials"
      securityContext:
        runAsNonRoot: true
```

Current behavior: deployment.yaml snippet thats generated using helmify
```
 imagePullSecrets:
      - name: myRegCredentials
    
 securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}
```

Expected behavior: deployment.yaml 
```
 imagePullSecrets: {{- toYaml .Values.controllerManager.imagePullSecrets | nindent
        8 }}
      
securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}

```
and values.yaml
```
imagePullSecrets:
  - name: myRegCredentials
podSecurityContext:
    runAsNonRoot: true
```

Is there an option to generate the above using helmify?
