### ISSUE TITLE
[BUG] Incorrect indent with `matchLabels`

### ISSUE THREAD

**Issue by kerthcet** [arttor/helmify#169]
This is how the yaml looks like after applying `$(KUSTOMIZE) build config/default | $(HELMIFY) -crd-dir`:

```
{{- if .Values.prometheus.enable }}
{{- if not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") }}
{{- fail "The cluster does not support the required API resource `monitoring.coreos.com/v1/ServiceMonitor`." }}
{{- end }}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ include "chart.fullname" . }}-prometheus
spec:
  serviceAccountName: {{ include "chart.fullname" . }}-prometheus
  # Associated ServiceMonitor selector
  serviceMonitorSelector:
    # Need to match the label in ServiceMonitor
    # https://github.com/kubernetes-sigs/jobset/blob/main/config/components/prometheus/monitor.yaml#L7
    matchLabels:
      control-plane: controller-manager
      {{- include "chart.selectorLabels" . | nindent 4 }}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
{{- end }}
```

So obviously the `spec.serviceMonitorSelector.matchLabels` is not right, the `chart.selectorLabels` should have nindent 6 which causes installation error: 
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Prometheus.spec.serviceMonitorSelector): unknown field "app.kubernetes.io/instance" in com.coreos.monitoring.v1.Prometheus.spec.serviceMonitorSelector, ValidationError(Prometheus.spec.serviceMonitorSelector): unknown field "app.kubernetes.io/name" in com.coreos.monitoring.v1.Prometheus.spec.serviceMonitorSelector]
make: *** [helm-install] Error 1
```
