### ISSUE TITLE
resolving claimName of PersistentVolumeClaim

### ISSUE THREAD

**Issue by wingsuitist** [arttor/helmify#18]
The metadata.name of PersistentVolumeClaim get extended by the full name.
References to the PersistentVolumeClaim in pod.spec.volumes.persistentVolumeClaim.claimName do not get adapted.

demo.yaml:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /test
      name: demo
  volumes:
  - name: demo
    persistentVolumeClaim:
      claimName: test-storage
```
