### ISSUE TITLE
ERRO[0000] wrong image format: XXX_production_traefik"

### ISSUE THREAD

**Issue by scheung38** [arttor/helmify#40]
kompose --file production.yml -o $HOME/Documents/arthur_aks/arthur-kompose-manifests/production convert -c --volumes hostPath

![Screenshot 2022-05-28 at 03 39 24](https://user-images.githubusercontent.com/1273014/170806567-568b02e3-b64f-420a-a602-1f03b7f20b8a.png)

Then using helmify:

awk 'FNR==1 && NR!=1  {print "---"}{print}' $HOME/Documents/arthur_aks/arthur-kompose-manifests/production/templates/*.yaml | helmify $HOME/Documents/arthur_aks/arthur-helmify

ERRO[0000] helmify finished with error                   error="wrong image format: arthur_paf_production_traefik"

This is the production.yaml (scaffolding from cookiecutter-django)

```
version: '3'

volumes:
![Screenshot 2022-05-28 at 03 36 18](https://user-images.githubusercontent.com/1273014/170806461-2ca470b6-b5bd-4621-9a48-d45cef7299f7.png)

  production_mongodb_data:
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: arthuracr.azurecr.io/arthur_paf_production_django:v1.0.0
    container_name: arthur_paf_production_django
    # platform: linux/x86_64
    depends_on:
      - mongo
    volumes:
      - .:/app:z
      - ../RTL_data/_PAF_Data_samples/PAF_MAIN_FILE:/uploaddata

    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mongodb
    ports:
      - "8000:8000"
      - "3000:3000"
    command: /start
    stdin_open: true
    tty: true

  mongo:
    image: mongo:5.0.6
    container_name: "mongo"
    restart: always
    env_file:
      - ./.envs/.production/.mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<USERNAME>
      - MONGO_INITDB_ROOT_PASSWORD=<PASSWORD>
      - MONGO_INITDB_DATABASE=<DATABASE>
      - MONGO_INITDB_USERNAME=<USERNAME> 
      - MONGO_INITDB_PASSWORD=<PASSWORD>
    volumes:
      - production_mongodb_data:/data/db
      # - ${PWD}/_data/mongo:/data/db
      # - ${PWD}/docker/_mongo/fixtures:/import
      # - ${PWD}/docker/_mongo/scripts/init.sh:/docker-entrypoint-initdb.d/setup.sh
    ports:
      - 27017:27017

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: arthur_paf_production_traefik
    container_name: arthur_paf_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
```

helmify -version
Version:    0.3.12
Build Time: 2022-05-17T09:02:12Z
Git Commit: 3634ef55f022db202f123e43e55ebb15161e1892

helm version --short
v3.7.1+g1d11fcb

k version --short                                                                          
Client Version: v1.22.2
Server Version: v1.21.9

Mac: 12.4

traefik-deployment.yaml:
```

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: $HOME/.asdf/installs/kompose/1.26.0/bin/kompose --file production.yml -o $HOME/Documents/arthur_aks/arthur-kompose-manifests/production convert -c --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: $HOME/.asdf/installs/kompose/1.26.0/bin/kompose --file production.yml -o $HOME/Documents/arthur_aks/arthur-kompose-manifests/production convert -c --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
        - image: arthur_paf_production_traefik
          name: arthur-paf-production-traefik
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /etc/traefik/acme
              name: production-traefik
      restartPolicy: Always
      volumes:
        - hostPath:
            path: $HOME/Documents/arthur_paf
          name: production-traefik
status: {}

```

traefik-service.yaml:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: $HOME/.asdf/installs/kompose/1.26.0/bin/kompose --file production.yml -o $HOME/Documents/arthur_aks/arthur-kompose-manifests/production convert -c --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: traefik
status:
  loadBalancer: {}



```
