### ISSUE TITLE
Wrong templating in certificate if chart name is the same as namespace name

### ISSUE THREAD

**Issue by KaiReichart** [arttor/helmify#53]
The generated Certificate looks like this:

``` yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "busola-operator.fullname" . }}-serving-cert
  labels:
  {{- include "busola-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "{{ .Release.Namespace }}.fullname" . }}-$(SERVICE_NAME).$(SERVICE_NAMESPACE).svc'
  - '{{ include "{{ .Release.Namespace }}.fullname" . }}-$(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: '{{ include "busola-operator.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert
```

Under `spec.dnsNames` the template is `{{ include "{{ .Release.Namespace }}.fullname" . }}` although it should be ` {{ include "busola-operator.fullname" . }}`

I am using helmify version 0.3.7 

It works fine when the chart name is different to the namespace name, this only happens when both are the same

**Comment by arttor** [comment]
HI, @KaiReichart , can you please try to upgrade to [the latest version](https://github.com/arttor/helmify/releases/tag/v0.3.18)?
The issue might be fixed in #42

**Comment by KaiReichart** [comment]
Hi @arttor 
Unfortunately it persists in the latest version

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "busola-operator.fullname" . }}-serving-cert
  labels:
  {{- include "busola-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "{{ .Release.Namespace }}.fullname" . }}-$(SERVICE_NAME).$(SERVICE_NAMESPACE).svc'
  - '{{ include "{{ .Release.Namespace }}.fullname" . }}-$(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.{{
    .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "busola-operator.fullname" . }}-selfsigned-issuer'
  secretName: webhook-server-cert
```
