### ISSUE TITLE
Allow more configuration to be customised 

### ISSUE THREAD

**Issue by smitthakkar96** [arttor/helmify#59]
The generated helm chart should allow changing things like:

- `annotations`
- `nodeSelector`
- `affinity` rules
- etc

It would be great if we could support a config file where the user can specify schema/attribute name and field-ref/s and helmify will automatically templatize it. 

Example:
``` yaml
vars:
- name: annotations
  optional: true
  objref:
    kind: Deployment
    group: apps
    version: v1
    name: xyz
  fieldrefs:
    - fieldpath: spec.template.metadata.annotation
```

PS: If this the community and maintainers are interested in I am happy to contribute
