### ISSUE TITLE
Helmify Repo Contribution

### ISSUE THREAD

**Issue by jsitu777** [arttor/helmify#64]
Hi,

I'm a developer in AWS working on k8s ML platform/toolings. I recently came across your helmify tool that seems to solve the same problem we had a while ago.

At first we were deploying our program with kustomize but in our recent release we are supporting both helm and terraform. You can check out our repo: https://github.com/awslabs/kubeflow-manifests

I wonder if we can contribute back to the repo instead of solving the same thing.

It will be helpful if you can:
* Give a brief introduction about yourself
* Who is maintaining the repo? I see there are 13 contributors so far and it seems to be pretty well maintained (last commit was 7 hours ago), but it seems like you do the majority of the commits.
* I see that it's under MIT license, are there other licensing issues you want us to be aware of?

**Comment by arttor** [comment]
Hi, i am really happy to hear that helmify can be used in such a big and important project, and very welcome to contributions!

- I started this project when I was working on [gardener onmetal project](https://github.com/onmetal) to convert kustomize to helm.
- the project is maintained by me but now I do mostly bugfixes and code reviews. It's hard to find time to work on big feature requests.
- I see no problems with the current MIT license but can change it to any other more open license if needed.

If you have any other questions, we can continue the discussion here or you can email me at torubarov.a.a@gmail.com

**Comment by arttor** [comment]
Hi, generated chart utilized to use helm namespace options. So helmify trims namespaces from input manifests and expects that all resources are in the same namespace or global. Then you can set and create an arbitrary namespace for a chart with `helm install ... -n <my-namespace> --create-namespace`.  


To put crds in a separate dir, you can run helmify with `-crd-dir` option (see help command or readme). This option is disabled by default for backward compatibility.

 
Unfortunately, all docs for this project are in the readme or in `helmify -h` command. Please tell me if something missing.

**Comment by jsitu777** [comment]
How does the tool handle the manifest that the kind is not listed:
deployment
daemonset
service, Ingress
PersistentVolumeClaim
RBAC (serviceaccount, (cluster-)role, (cluster-)rolebinding)
configs (configmap, secret)
webhooks (cert, issuer, ValidatingWebhookConfiguration)
custom resource definitions

I see sometimes a single yaml file will contain two files in there, and when you run helm install, the pod error out

example of one of the generated template file
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knative-serving.fullname" . }}-activator-service
  labels:
    app: activator
    app.kubernetes.io/component: activator
    serving.knative.dev/release: v1.2.5
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.activatorService.type }}
  selector:
    app: activator
  {{- include "knative-serving.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.activatorService.ports | toYaml | nindent 2 -}}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "knative-serving.fullname" . }}-activator-service
  labels:
  {{- include "knative-serving.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      app: activator
```

it might be due to the fact that the kind is not listed.
